### ISSUE TITLE
About the dimension of W_e in Hyper-Network

### ISSUE THREAD

**Issue by mzshuo** [deepkashiwa20/MegaCRN#6]
Hi,
Congratulations for your good job!
I have one question here. I think the matrix W_E should have the dimension of N * \phi as your codes said, rather than d * e in your paper. Correct me if I am wrong.

<img width="531" alt="截屏2023-11-05 14 49 47" src="https://github.com/deepkashiwa20/MegaCRN/assets/44536982/1cbf5fcf-62b2-4c86-a4a9-2bb2e93532d7">

https://github.com/deepkashiwa20/MegaCRN/blob/ac03024c6ad0f6ade405a514f9774efd035389bc/model/MegaCRN.py#L153

Best regards.

**Comment by deepkashiwa20** [comment]
Hi, you are right. Sorry for the inconvience. Actually, our original code is model_futurework/MegaCRNx.py, which has an information leak bug. We revised the code but failed to revised the paper perfectly. I recommend you also check the model_futurework/MegaCRNx.py code and try to understand what we originally would like to do. Pay attention to information leak when doing graph learning (B, N, N) -> (N, N). StemGNN also has the same bug. You could check issue #1.

**Comment by mzshuo** [comment]
That makes sense. Thanks for your reply~
